[project]
name = "mcp_hello_world"
version = "0.1.0"
description = "最简单的加法运算器的MCP调用"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [    
    "mcp[cli]>=1.6.0",
    "openai>=1.75.0",
    "python-dotenv>=1.1.0",
]
